[package]
name = "rustual-boy"
version = "0.1.0"
authors = ["ferris <yupferris@gmail.com>", "The Rustual Boy contributors"]

[features]
logging = []

[dependencies]
encoding = "0.2"
nom = "^1.2.3"
minifb = "0.9.0"
cpal = "0.4.2"
futures = "0.1.1"
