[package]
name = "rustual-boy-serialization"
version = "0.1.0"
authors = ["ferris <yupferris@gmail.com>"]

[dependencies]
rustual-boy-core = { path="../rustual-boy-core" }
serde = "1.0"
serde_derive = "1.0"
serde_bytes="0.10"
bincode = "1.0"
lz4 = "*"
